config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  root 'welcome#index'

  resources :customers do
    get :purchases
  end
  resources :branches
  resources :products
  resources :purchases
  resources :logs, only: [:index, :show]

  resources :reports, only: [:index] do
    collection do
      match :purchases, via: [:get, :post]
      post :weekly
    end
  end

  mount ResqueWeb::Engine => '/resque_web'
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  include Loggable

  has_many :purchases

  validates :name, presence: true
  validates :address, presence: true

  def to_s
    "#{name}, #{address}"
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: [:show, :edit, :update, :destroy]

  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
  end

  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch, notice: 'Branch was successfully created.' }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url, notice: 'Branch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_params
      params.require(:branch).permit(:name, :address)
    end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.erb
<%= form_for(@branch) do |f| %>
  <% if @branch.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @branch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

app/views/branches/edit.html.erb
<h4>Editing Branch</h4>

<%= render 'form' %>

<%= link_to 'Show', @branch %> |
<%= link_to 'Back', branches_path %>

app/views/branches/index.html.erb
<h4>Branches</h4>

<div class="divider"></div>

<table class="responsive-table bordered striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @branches.each do |branch| %>
      <tr>
        <td><%= branch.name %></td>
        <td><%= branch.address %></td>
        <td><%= link_to 'Show', branch %></td>
        <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
        <td><%= link_to 'Destroy', branch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Branch', new_branch_path, class: 'btn' %>

app/views/branches/new.html.erb
<h4>New Branch</h4>

<%= render 'form' %>

app/views/branches/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @branch.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @branch.address %>
</p>

<%= link_to 'Edit', edit_branch_path(@branch) %> |
<%= link_to 'Back', branches_path %>