config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  root 'welcome#index'

  resources :customers do
    get :purchases
  end
  resources :branches
  resources :products
  resources :purchases
  resources :logs, only: [:index, :show]

  resources :reports, only: [:index] do
    collection do
      match :purchases, via: [:get, :post]
      post :weekly
    end
  end

  mount ResqueWeb::Engine => '/resque_web'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  include Loggable

  has_many :purchases

  validates :number, presence: true, uniqueness: true
  validates :name, presence: true

  scope :not_void, -> { where.not(name: '(Void)') }

  def to_s
    "#{number} - #{name}"
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy, :purchases]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.order :name
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def purchases
    @purchases = @customer.purchases
    @total_purchases = @purchases.reduce(0) { |a, e| a + e.price }

    respond_to do |format|
      format.html do
        flash.now[:notice] = 'Customer does not have purchases yet' if @purchases.empty?
      end
      format.json { render 'purchases/index' }
      format.pdf
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      id = params[:id] || params[:customer_id]
      @customer = Customer.find(id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:number, :name, :detail)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_field :detail %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h4>Editing Customer</h4>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h4>Customers</h4>

<div class="divider"></div>

<table class="responsive-table bordered striped">
  <thead>
    <tr>
      <th>Number</th>
      <th>Name</th>
      <th>Detail</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.number %></td>
        <td><%= customer.name %></td>
        <td><%= customer.detail %></td>
        <td><%= link_to 'Purchases', customer_purchases_path(customer) %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path, class: 'btn' %>

app/views/customers/new.html.erb
<h4>New Customer</h4>

<%= render 'form' %>

app/views/customers/purchases.html.erb
<% if @purchases.any? %>
  <h4>Purchases Report</h4>
  <div class="divider"></div>

  <div class="buffer-bottom">
    <a href="./purchases.pdf" class="btn red lighten-2">PDF</a>
    <a href="./purchases.json" class="btn blue lighten-2">JSON</a>
  </div>

  <div class="row">
    <div class="col s12 m10 offset-m1">
      <div class="card padding-10">
        <table class="responsive-table bordered striped">
          <thead>
            <tr>
              <th>Customer:</th>
              <td colspan="3">
                <%= link_to @customer, customer_path(@customer) %>
              </td>
            </tr>
            <tr>
              <th>Product Id</th>
              <th>Name</th>
              <th>Branch</th>
              <th class="right-align">Price</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th class="right-align" colspan="3">Total</th>
              <th class="right-align"><%= number_to_currency(@total_purchases) %></th>
            </tr>
          </tfoot>
          <tbody>
            <% @purchases.each do |p| %>
              <tr>
                <td><%= p.product.id %></td>
                <td><%= link_to p.product.name, product_path(p.product) %></td>
                <td><%= p.branch.name %></td>
                <td class="right-align"><%= number_to_currency(p.price) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>

app/views/customers/show.html.erb
<p>
  <strong>Number:</strong>
  <%= @customer.number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @customer.detail %>
</p>

<%= link_to 'Purchases', customer_purchases_path(@customer) %> |
<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>