config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  root 'welcome#index'

  resources :customers do
    get :purchases
  end
  resources :branches
  resources :products
  resources :purchases
  resources :logs, only: [:index, :show]

  resources :reports, only: [:index] do
    collection do
      match :purchases, via: [:get, :post]
      post :weekly
    end
  end

  mount ResqueWeb::Engine => '/resque_web'
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  include Loggable

  has_many :purchases

  validates :name, presence: true
  validates :address, presence: true

  def to_s
    "#{name}, #{address}"
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  include Loggable

  has_many :purchases

  validates :number, presence: true, uniqueness: true
  validates :name, presence: true

  scope :not_void, -> { where.not(name: '(Void)') }

  def to_s
    "#{number} - #{name}"
  end
end

app/models/log.rb
class Log < ActiveRecord::Base
  def self.create_entry(operation, model)
    create operation: operation,
           model_class: model.class,
           model_id: model.id,
           model_json: model.to_json
  end

  def model_json_pretty
    JSON.pretty_generate(JSON.parse(model_json))
  end

  def to_s
    "#{model_class}: #{model_id}"
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  include Loggable

  has_many :purchases, through: :order_details

  before_create do
    self.number = Setting.next_order_number
    Setting.next_order_number += 1
  end
end

app/models/order_detail.rb
class OrderDetail < ActiveRecord::Base
  include Loggable

  belongs_to :order
  belongs_to :purchase
end

app/models/product.rb
class Product < ActiveRecord::Base
  include Loggable

  has_many :purchases

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: true

  scope :not_void, -> { where.not(name: '(Void)') }

  def to_s
    "#{id} - #{name}"
  end
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  include Loggable

  belongs_to :customer
  belongs_to :product
  belongs_to :branch

  validates :customer, presence: true
  validates :price, presence: true
  validates :product, presence: true
  validates :branch, presence: true

  before_validation do
    unless price
      self.price = product.price if product
    end
  end

  after_create do
    OrderDetail.create order: Order.create, purchase: self
  end
end

app/models/report.rb
class Report
  @@from = 1.week.ago.at_midnight

  def self.weekly
    {
      max: extreme_diff,
      min: extreme_diff(:min),
      avg: avg_diff,
      count: purchases_count,
      profits: profits,
      purchases_minute: purchases_minute
    }
  end

  def self.extreme_diff(type = :max, from = @@from)
    order = 'desc'
    order = 'asc' if type == :min

    ActiveRecord::Base.connection.execute("select
      a.id as product_id,
      a.name as product_name,
      b.id as purchase_id,
      b.created_at as purchase_date,
      a.price as product_price,
      b.price as purchase_price,
      b.price - a.price as diff
      from products as a join purchases as b on a.id = b.product_id
      where b.price - a.price != 0 and b.created_at >= '#{from}'
      order by abs(diff) #{order}
      limit 1").first
  end

  def self.avg_diff(from = @@from)
    ActiveRecord::Base.connection.execute("select
      avg(abs(b.price - a.price)) as avg_diff
      from products as a join purchases as b on a.id = b.product_id
      where b.price - a.price != 0 and b.created_at >= '#{from}'").first[0]
  end

  def self.purchases_count(from = @@from)
    Purchase.where('created_at >= ?', from).count
  end

  def self.profits(from = @@from)
    Purchase.where('created_at >= ?', from).sum :price
  end

  def self.purchases_minute(from = @@from)
    minutes = (Time.current.tomorrow.at_midnight - from) / 60
    purchases_count / minutes
  end
end

app/models/setting.rb
class Setting < RailsSettings::CachedSettings
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show]

  def index
    @logs = Log.all
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end

  def purchases
    return unless request.post?

    customer_number = params[:customer_number].strip
    customer = Customer.where(number: customer_number).first
    if customer
      redirect_to customer_purchases_path(customer)
    else
      flash.now[:warning] = "There is no customer with number '#{customer_number}'"
    end
  end

  def weekly
    ReportMailer.weekly.deliver_later
    @weekly_report_email = Setting.weekly_report_email
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @weekly_report_email = Setting.weekly_report_email
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MauroShop</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= csrf_meta_tags %>

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= favicon_link_tag %>
</head>
<body>
  <ul id="manage1" class="dropdown-content">
    <li><%= link_to 'Customers', customers_path %></li>
    <li><%= link_to 'Branches', branches_path %></li>
    <li><%= link_to 'Products', products_path %></li>
  </ul>
  <ul id="manage2" class="dropdown-content">
    <li><%= link_to 'Customers', customers_path %></li>
    <li><%= link_to 'Branches', branches_path %></li>
    <li><%= link_to 'Products', products_path %></li>
  </ul>

  <ul id="reports1" class="dropdown-content">
    <li><%= link_to 'Purchases', purchases_reports_path %></li>
    <li><%= link_to 'Weekly', weekly_reports_path %></li>
    <li class="divider"></li>
    <li><%= link_to 'Logs', logs_path %></li>
  </ul>
  <ul id="reports2" class="dropdown-content">
    <li><%= link_to 'Purchases', purchases_reports_path %></li>
    <li><%= link_to 'Weekly', weekly_reports_path %></li>
    <li class="divider"></li>
    <li><%= link_to 'Logs', logs_path %></li>
  </ul>

  <nav>
    <div class="nav-wrapper">
      <%= link_to 'MauroShop', root_path, class: 'brand-logo buffer-left' %>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to 'New Purchase', new_purchase_path %></li>
        <li>
          <a class="dropdown-button" href="#!" data-activates="reports1">
            Reports
            <i class="material-icons right">arrow_drop_down</i>
          </a>
        </li>
        <li>
          <a class="dropdown-button" href="#!" data-activates="manage1">
            Manage
            <i class="material-icons right">arrow_drop_down</i>
          </a>
        </li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><%= link_to 'New Purchase', new_purchase_path %></li>
        <li>
          <a class="dropdown-button" href="#!" data-activates="reports2">
            Reports
            <i class="material-icons right">arrow_drop_down</i>
          </a>
        </li>
        <li>
          <a class="dropdown-button" href="#!" data-activates="manage2">
            Manage
            <i class="material-icons right">arrow_drop_down</i>
          </a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="container main-container">
    <div class="buffer-bottom">
      <% flash.each do |name, msg| -%>
        <%= content_tag :h5, msg, class: "z-depth-1 center-align alert alert-#{name}" %>
      <% end -%>
    </div>

    <%= yield %>
  </div>

  <footer class="page-footer grey lighten-2">
    <div class="footer-copyright grey lighten-3">
      <div class="container">
        <a class="grey-text text-darken-4" href="http://github.com/mporras/mauroshop">Mauro Porras P.</a>
      </div>
    </div>
  </footer>

  <%= javascript_include_tag 'application' %>
</body>
</html>